### ISSUE TITLE
can't modify frozen NilClass on service delete

### ISSUE THREAD

**Issue by PlugIN73** [vongrippen/bitbucket#37]
Hello! I'm doing this:

       bitbucket.repos.services.delete repo_organization, repo_name, webhook_id

And service was deleted, but exception was raised:

can't modify frozen NilClass
/vagrant/vendor/bundle/ruby/2.2.0/gems/bitbucket_rest_api-0.1.5/lib/bitbucket_rest_api/response/helpers.rb:17:in `block in on_complete'
/vagrant/vendor/bundle/ruby/2.2.0/gems/bitbucket_rest_api-0.1.5/lib/bitbucket_rest_api/response/helpers.rb:17:in `instance_eval'
/vagrant/vendor/bundle/ruby/2.2.0/gems/bitbucket_rest_api-0.1.5/lib/bitbucket_rest_api/response/helpers.rb:17:in `on_complete'
/vagrant/vendor/bundle/ruby/2.2.0/gems/faraday-0.8.9/lib/faraday/response.rb:9:in `block in call'
/vagrant/vendor/bundle/ruby/2.2.0/gems/faraday-0.8.9/lib/faraday/response.rb:63:in `on_complete'
/vagrant/vendor/bundle/ruby/2.2.0/gems/faraday-0.8.9/lib/faraday/response.rb:8:in `call'
/vagrant/vendor/bundle/ruby/2.2.0/gems/faraday_middleware-0.9.1/lib/faraday_middleware/request/encode_json.rb:23:in `call'
/vagrant/vendor/bundle/ruby/2.2.0/gems/faraday_middleware-0.9.1/lib/faraday_middleware/request/oauth.rb:42:in `call'
/vagrant/vendor/bundle/ruby/2.2.0/gems/faraday-0.8.9/lib/faraday/request/url_encoded.rb:14:in `call'
/vagrant/vendor/bundle/ruby/2.2.0/gems/faraday-0.8.9/lib/faraday/request/multipart.rb:13:in `call'
/vagrant/vendor/bundle/ruby/2.2.0/gems/faraday-0.8.9/lib/faraday/connection.rb:253:in `run_request'
/vagrant/vendor/bundle/ruby/2.2.0/gems/faraday-0.8.9/lib/faraday/connection.rb:106:in `delete'
/vagrant/vendor/bundle/ruby/2.2.0/gems/bitbucket_rest_api-0.1.5/lib/bitbucket_rest_api/request.rb:41:in `request'
/vagrant/vendor/bundle/ruby/2.2.0/gems/bitbucket_rest_api-0.1.5/lib/bitbucket_rest_api/request.rb:27:in `delete_request'
/vagrant/vendor/bundle/ruby/2.2.0/gems/bitbucket_rest_api-0.1.5/lib/bitbucket_rest_api/repos/services.rb:99:in `delete'
/vagrant/lib/bitbucket_manager.rb:34:in `delete_web_hook'

I'm doing something wrong?

**Comment by PlugIN73** [comment]
Hm, I add github url to my Gemfile and now it works. I'm sorry!
